### ISSUE TITLE
DGL Error. 

### ISSUE THREAD

**Issue by Xtremely-Doped-Punk** [zshicode/GNN-for-text-classification#4]
On running the main file I get the error " 'Cannot assign node feature "{}" on device {} to a graph on' dgl._ffi.base. "
The details are given below. Please let me know on how to resolve it.

 On checking the DGL official website the  version dgl-cu101(0.4.1) is not available

The version I have installed is (Windows) DGL-cuda11.3, torch-1.11.0+cu115.

Traceback (most recent call last):
  File "D:\STUDIES\workspaces\Python\GNN-for-text-classification-master\main.py", line 305, in <module>
    logits = model(t_features)
  File "D:\STUDIES\workspaces\Python\Compiler\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\STUDIES\workspaces\Python\GNN-for-text-classification-master\main.py", line 235, in forward
    x = self.gcn1(features)
  File "D:\STUDIES\workspaces\Python\Compiler\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\STUDIES\workspaces\Python\GNN-for-text-classification-master\main.py", line 118, in forward
    g.ndata['h'] = feat.mm(getattr(self, 'W'))
  File "D:\STUDIES\workspaces\Python\Compiler\lib\site-packages\dgl\view.py", line 84, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key : val})
  File "D:\STUDIES\workspaces\Python\Compiler\lib\site-packages\dgl\heterograph.py", line 4122, in _set_n_repr
    raise DGLError('Cannot assign node feature "{}" on device {} to a graph on'
dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.

**Comment by zshicode** [comment]
Code in this repository is based on previous version of PyTorch and DGL. So if you use the latest version of PyTorch and DGL to run the code, some bugs may occur.

**Comment by zshicode** [comment]
The code is run on PyTorch 1.3.1 with CUDA 10.1 and DGL 0.4.1.
