### ISSUE TITLE
FileNotFoundError dgl.dll (or one of its dependencies)

### ISSUE THREAD

**Issue by ghost** [zshicode/GNN-for-text-classification#7]
(base) C:\Users\Ramy>cd C:\Users\Ramy\Desktop\GCNTEST\GNN-for-text-classification-master

(base) C:\Users\Ramy\Desktop\GCNTEST\GNN-for-text-classification-master>python main.py --model GCN --cuda True
Traceback (most recent call last):
  File "C:\Users\Ramy\Desktop\GCNTEST\GNN-for-text-classification-master\main.py", line 13, in <module>
    import dgl
  File "C:\Users\Ramy\anaconda3\lib\site-packages\dgl\__init__.py", line 13, in <module>
    from .backend import load_backend, backend_name
  File "C:\Users\Ramy\anaconda3\lib\site-packages\dgl\backend\__init__.py", line 95, in <module>
    load_backend(get_preferred_backend())
  File "C:\Users\Ramy\anaconda3\lib\site-packages\dgl\backend\__init__.py", line 41, in load_backend
    from .._ffi.base import load_tensor_adapter # imports DGL C library
  File "C:\Users\Ramy\anaconda3\lib\site-packages\dgl\_ffi\base.py", line 44, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "C:\Users\Ramy\anaconda3\lib\site-packages\dgl\_ffi\base.py", line 34, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "C:\Users\Ramy\anaconda3\lib\ctypes\__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Ramy\anaconda3\lib\site-packages\dgl\dgl.dll' (or one of its dependencies). Try using the full path with constructor syntax.

(base) C:\Users\Ramy\Desktop\GCNTEST\GNN-for-text-classification-master>

**Comment by zshicode** [comment]
Code in this repository is based on previous version of PyTorch and DGL. The code is run on PyTorch 1.3.1 with CUDA 10.1 and DGL 0.4.1. So if you use the latest version of PyTorch and DGL to run the code, some bugs may occur.
